sudo: required

services:
  - docker

language: minimal

jobs:
  include:
    - stage: build and test
      before_install:
        - docker pull viktormalik/diffkemp-devel
      before_script:
        - mkdir build
        - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then tests/regression/clean_test.sh all; fi
      script: 
        - docker run -v $PWD:/diffkemp:Z -w /diffkemp viktormalik/diffkemp-devel /bin/bash -c \
          "cd build; cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_LLREVE=ON; ninja; cd .."
        - docker run -v $PWD:/diffkemp:Z -w /diffkemp viktormalik/diffkemp-devel /bin/bash -c \
          "pytest tests/unit_tests"
        - docker run -v $PWD:/diffkemp:Z -w /diffkemp viktormalik/diffkemp-devel /bin/bash -c \
          "pytest tests/regression"
    
    - stage: linter
      install:
        - pip install --user flake8
      script:
        - flake8 diffkemp --exclude=llreve --ignore=F403,F405,W504
        - flake8 tests

