language: python
python: 3.6
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - clang-5.0
      - cpio
      - cscope
      - gcc-7
      - g++-7
      - kmod
      - libelf-dev
      - libssl-dev
      - llvm-5.0
      - llvm-5.0-dev
      - ninja-build
      - rpm2cpio

before_install:
  - sudo ln -s /usr/lib/llvm-5.0/include/llvm /usr/local/include/llvm
  - sudo ln -s /usr/lib/llvm-5.0/include/llvm-c /usr/local/include/llvm-c
  - sudo update-alternatives --install /usr/local/bin/llvm-config llvm-config /usr/bin/llvm-config-5.0 100
  - sudo update-alternatives --install /usr/local/bin/clang clang /usr/bin/clang-5.0 100
  - sudo update-alternatives --install /usr/local/bin/opt opt /usr/bin/opt-5.0 100
  - sudo update-alternatives --install /usr/local/bin/llvm-link llvm-link /usr/bin/llvm-link-5.0 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - export PATH=`echo $PATH | sed -e 's#:/usr/local/clang-7.0.0/bin##'`

install:
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - ninja
  - cd ..
  - pip3 install -r requirements.txt
  - pip3 install -e .

script:
  - pytest tests
  - flake8 diffkemp --exclude=llreve --ignore=F403,F405,W504
  - flake8 tests

