language: python
python: 3.6
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - bc
      - clang-8
      - cpio
      - cscope
      - gcc-7
      - g++-7
      - kmod
      - libelf-dev
      - libssl-dev
      - llvm-8
      - llvm-8-dev
      - ninja-build
      - rpm2cpio

before_install:
  - sudo ln -s /usr/lib/llvm-8/include/llvm /usr/local/include/llvm
  - sudo ln -s /usr/lib/llvm-8/include/llvm-c /usr/local/include/llvm-c
  - sudo update-alternatives --install /usr/local/bin/llvm-config llvm-config /usr/bin/llvm-config-8 100
  - sudo update-alternatives --install /usr/local/bin/clang clang /usr/bin/clang-8 100
  - sudo update-alternatives --install /usr/local/bin/opt opt /usr/bin/opt-8 100
  - sudo update-alternatives --install /usr/local/bin/llvm-link llvm-link /usr/bin/llvm-link-8 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - export PATH=`echo $PATH | sed -e 's#:/usr/local/clang-7.0.0/bin##'`

install:
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - ninja
  - cd ..
  - pip3 install -r requirements.txt
  - pip3 install -e .

before_script:
  - git clone https://github.com/viktormalik/rhel-kernel-get.git
  - pip3 install -r rhel-kernel-get/requirements.txt
  - rhel-kernel-get/rhel-kernel-get.py 3.10.0-514.el7 --output-dir kernel --kabi
  - rhel-kernel-get/rhel-kernel-get.py 3.10.0-693.el7 --output-dir kernel --kabi
  - rhel-kernel-get/rhel-kernel-get.py 3.10.0-862.el7 --output-dir kernel --kabi
  - rhel-kernel-get/rhel-kernel-get.py 3.10.0-957.el7 --output-dir kernel --kabi
  - rhel-kernel-get/rhel-kernel-get.py 3.10 --output-dir kernel
  - rhel-kernel-get/rhel-kernel-get.py 4.11 --output-dir kernel

script:
  - pytest tests
  - flake8 diffkemp --exclude=llreve --ignore=F403,F405,W504
  - flake8 tests

