name: Code style

on: [push, pull_request]

jobs:
  code-style-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v10

      - name: Check Coding Style
        working-directory: ${{ github.workspace }}
        shell: bash
        run: nix develop .#diffkemp-llvm17 --command tools/check-clang-format.sh -d

  code-style-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        working-directory: ${{ github.workspace }}
        shell: bash
        run: pip install flake8

      - name: Check Coding Style
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          flake8 diffkemp --ignore=F403,F405,W504
          flake8 tests

  code-style-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci --prefix view

      - name: Check coding style with ESLint
        run: npm run lint --prefix view
