root: true
extends:
  - react-app
  - react-app/jest
  - airbnb
  # From React 17 importing React is not necessary for JSX
  - plugin:react/jsx-runtime
  - plugin:cypress/recommended
ignorePatterns:
  - public/
  - build/
rules:
  react/require-default-props: off
